version: "3"
services: 
    api:
        container_name: api
        restart: always
        build: ./
        ports: 
            - "3000:3000"
        depends_on:
            - postgres
    client:
        container_name: client
        restart: always
        build: ./frontend
        ports: 
            - "4200:4200"
        links:
            - api
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        expose: 
            - "5432"
        expose: 
            - "5432:5432"